[nixpacks]
providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = ["cd apps/web && npm ci"]

[phases.build]
cmds = ["cd apps/web && npm run build"]

[start]
cmd = "cd apps/web && npm run preview"
